services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"    # REST / Console
      - "50051:50051"  # gRPC
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      QUERY_DEFAULTS_LIMIT: 25
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
